### ISSUE TITLE
List of implementations?

### ISSUE THREAD

**Issue by yogaraptor** [micro-api/micro-api#9]
I love the idea of micro-api but it's one of those lovely but unfortunate names which is really ungoogle-able. I'm struggling to find any server or client serialisers which obviously makes selling it to devs pretty tricky. The only one I know of is [fortune-micro-api](https://github.com/fortunejs/fortune-micro-api). Unfortunately my current project is a Django app :)

Is there a list somewhere of known implementations?

Edit: hadn't noticed that you're the author of fortune ;)

**Comment by gr0uch** [comment]
All of my open-source projects are experiments which are used by me almost exclusively, and incidentally by other people. They happen to be documented well because I can never remember what I wrote.

As far as I know, that's the only implementation. I guess it wouldn't be too hard to take an existing JSON-LD implementation and remove parts to fit Micro API, but there are also very few JSON-LD APIs in the wild.

**Comment by yogaraptor** [comment]
Thanks for the insight! Your documentation is impeccable for something mainly to remind yourself of how what you wrote works, kudos :)
